### ISSUE TITLE
LLVM 3.9 compatibility: LLVMLinkModules was deprecated

### ISSUE THREAD

**Issue by ilovezfs** [nickg/nvc#310]
nvc cannot currently build with LLVM 3.9 because LLVMLinkModules was deprecated in favor of LLVMLinkModules2. The error is
```
  CXXLD    bin/nvc
Undefined symbols for architecture x86_64:
  "_LLVMLinkModules", referenced from:
      _link_context_bc_fn in libcgen.a(lib_libcgen_a-link.o)
     (maybe you meant: _LLVMLinkModules2)
ld: symbol(s) not found for architecture x86_64
```

As indicated in the LLVM 3.8 release notes,

>The C API function LLVMLinkModules is deprecated. It will be removed in the 3.9 release. Please migrate to LLVMLinkModules2. Unlike the old function the new one
>
>        Doesn’t take an unused parameter.
>        Destroys the source instead of only damaging it.
>        Does not record a message. Use the diagnostic handler instead.

A minimal patch to avoid the build failure is
```
diff --git a/src/link.c b/src/link.c
index 850de56..2592b84 100644
--- a/src/link.c
+++ b/src/link.c
@@ -158,8 +158,8 @@ static void link_context_bc_fn(lib_t lib, tree_t unit, FILE *deps)
          tree_remove_attr(unit, llvm_i);
 
       char *outmsg;
-      if (LLVMLinkModules(module, src, LLVMLinkerDestroySource, &outmsg))
-         fatal("LLVM link failed: %s", outmsg);
+      if (LLVMLinkModules2(module, src))
+         fatal("LLVM link failed");
    }
 }
```

A complete fix would use the the diagnostic handler to print a specific message as well.

**Comment by nickg** [comment]
Thanks, I've applied that
