### ISSUE TITLE
Fails to build with LLVM 4.0.0-rc2

### ISSUE THREAD

**Issue by ilovezfs** [nickg/nvc#313]
In anticipation of the imminent LLVM 4.0.0 release, I'm testing whether each of the reverse dependencies of LLVM in Homebrew core are able to build. Unfortunately, the nvc build (b8cb16f36d62418471afd39a0d97d75340bb47dc) fails with
```
  CC       src/lib_libcgen_a-cgen.o
src/cgen.c:610:31: error: use of undeclared identifier 'LLVMNoUnwindAttribute'; did you mean 'LLVMIsStringAttribute'?
      LLVMAddFunctionAttr(fn, LLVMNoUnwindAttribute);
                              ^~~~~~~~~~~~~~~~~~~~~
                              LLVMIsStringAttribute
/usr/local/opt/llvm/include/llvm-c/Core.h:500:10: note: 'LLVMIsStringAttribute' declared here
LLVMBool LLVMIsStringAttribute(LLVMAttributeRef A);
         ^
src/cgen.c:1884:31: error: use of undeclared identifier 'LLVMNoUnwindAttribute'; did you mean 'LLVMIsStringAttribute'?
      LLVMAddFunctionAttr(fn, LLVMNoUnwindAttribute);
                              ^~~~~~~~~~~~~~~~~~~~~
                              LLVMIsStringAttribute
/usr/local/opt/llvm/include/llvm-c/Core.h:500:10: note: 'LLVMIsStringAttribute' declared here
LLVMBool LLVMIsStringAttribute(LLVMAttributeRef A);
         ^
src/cgen.c:2900:28: error: use of undeclared identifier 'LLVMNoUnwindAttribute'; did you mean 'LLVMIsStringAttribute'?
   LLVMAddFunctionAttr(fn, LLVMNoUnwindAttribute);
                           ^~~~~~~~~~~~~~~~~~~~~
                           LLVMIsStringAttribute
/usr/local/opt/llvm/include/llvm-c/Core.h:500:10: note: 'LLVMIsStringAttribute' declared here
LLVMBool LLVMIsStringAttribute(LLVMAttributeRef A);
         ^
src/cgen.c:2908:31: error: use of undeclared identifier 'LLVMReadOnlyAttribute'
      LLVMAddFunctionAttr(fn, LLVMReadOnlyAttribute);
                              ^
src/cgen.c:3005:28: error: use of undeclared identifier 'LLVMNoUnwindAttribute'; did you mean 'LLVMIsStringAttribute'?
   LLVMAddFunctionAttr(fn, LLVMNoUnwindAttribute);
                           ^~~~~~~~~~~~~~~~~~~~~
                           LLVMIsStringAttribute
/usr/local/opt/llvm/include/llvm-c/Core.h:500:10: note: 'LLVMIsStringAttribute' declared here
LLVMBool LLVMIsStringAttribute(LLVMAttributeRef A);
         ^
src/cgen.c:3079:28: error: use of undeclared identifier 'LLVMNoUnwindAttribute'; did you mean 'LLVMIsStringAttribute'?
   LLVMAddFunctionAttr(fn, LLVMNoUnwindAttribute);
                           ^~~~~~~~~~~~~~~~~~~~~
                           LLVMIsStringAttribute
/usr/local/opt/llvm/include/llvm-c/Core.h:500:10: note: 'LLVMIsStringAttribute' declared here
LLVMBool LLVMIsStringAttribute(LLVMAttributeRef A);
         ^
src/cgen.c:3569:31: error: use of undeclared identifier 'LLVMNoReturnAttribute'
      LLVMAddFunctionAttr(fn, LLVMNoReturnAttribute);
                              ^
src/cgen.c:3578:31: error: use of undeclared identifier 'LLVMNoReturnAttribute'
      LLVMAddFunctionAttr(fn, LLVMNoReturnAttribute);
                              ^
src/cgen.c:3587:31: error: use of undeclared identifier 'LLVMNoReturnAttribute'
      LLVMAddFunctionAttr(fn, LLVMNoReturnAttribute);
                              ^
src/cgen.c:3654:31: error: use of undeclared identifier 'LLVMNoUnwindAttribute'; did you mean 'LLVMIsStringAttribute'?
      LLVMAddFunctionAttr(fn, LLVMNoUnwindAttribute);
                              ^~~~~~~~~~~~~~~~~~~~~
                              LLVMIsStringAttribute
/usr/local/opt/llvm/include/llvm-c/Core.h:500:10: note: 'LLVMIsStringAttribute' declared here
LLVMBool LLVMIsStringAttribute(LLVMAttributeRef A);
         ^
10 errors generated.
make[1]: *** [src/lib_libcgen_a-cgen.o] Error 1
make: *** [all] Error 2
```
Full build log here: https://gist.github.com/ilovezfs/5e3636d0083e054ceeaa60db42c00fc9

**Comment by ilovezfs** [comment]
In case it helps: http://www.llvm.org/pre-releases/4.0.0/rc2/docs/ReleaseNotes.html
