### ISSUE TITLE
Error while running simulations (archlinux, llvm 3.6)

### ISSUE THREAD

**Issue by jck** [nickg/nvc#117]
LLVM ERROR: Target does not support MC emission!

Analysis and elaboration seem to work.

**Comment by jck** [comment]
Output of make check:
```
  CCLD     bin/test_parse
/usr/bin/ld: lib/libnvc.a(lexer.o): undefined reference to symbol 'pow@@GLIBC_2.2.5'
/usr/lib/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:1172: recipe for target 'bin/test_parse' failed
make[1]: *** [bin/test_parse] Error 1
Makefile:2076: recipe for target 'check-am' failed
make: *** [check-am] Error 2
```

**Comment by jck** [comment]
Using the '--native' flag during elaboration seems to work around the issue.

**Comment by nickg** [comment]
Yes I think the LLVM JIT interface changed between 3.5 and 3.6. I'll install 3.6 and fix it.

**Comment by nickg** [comment]
Can you see if the above commit fixes the `make check` link error?

**Comment by nickg** [comment]
JIT works with LLVM 3.6 now.

**Comment by jck** [comment]
Thanks, I just tried nvc with MyHDL's testsuite and all tests passed!

**Comment by nickg** [comment]
Great, thanks for testing that.
