### ISSUE TITLE
OS X 10.11 build failure for 1.3.0

### ISSUE THREAD

**Issue by ilovezfs** [nickg/nvc#365]
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/15688/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install_nvc/

```
  CC       src/object.o
  CC       src/lower.o
  CC       src/vcode.o
  CC       src/rt/rtkern.o
src/rt/rtkern.c:411:22: error: use of undeclared identifier 'CLOCK_MONOTONIC'
   if (clock_gettime(CLOCK_MONOTONIC, &ts) != 0)
                     ^
1 error generated.
make[1]: *** [src/rt/rtkern.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
```

Builds fine on 10.12 and 10.13.

**Comment by nickg** [comment]
Hi, could you test the patch above? It's on the `issue365` branch. I found this on SO but don't have an OS X machine to test.

**Comment by ilovezfs** [comment]
@nickg yes that seems to work :)

**Comment by ilovezfs** [comment]
@nickg and while I have your attention … https://github.com/nickg/nvc/issues/366

**Comment by nickg** [comment]
On the master branch now. I can make a 1.3.1 release once we've fixed the other issue.

**Comment by ilovezfs** [comment]
Awesome! Thanks :)
